Use list for systemfiles in userdata folder.
Signed-off-by: Ben Clark <ben@benjyc.uk>

diff --git a/distributions/openhab/src/main/resources/bin/backup b/distributions/openhab/src/main/resources/bin/backup
--- a/distributions/openhab/src/main/resources/bin/backup
+++ b/distributions/openhab/src/main/resources/bin/backup
@@ -44,12 +44,16 @@ setup(){
 
   WorkingDir="$(cd "$(dirname "$0")" && cd ../.. && pwd -P)"
 
-  if [ -z "$OPENHAB_CONF" ];       then OPENHAB_CONF="$WorkingDir/conf"; fi
-  if [ -z "$OPENHAB_USERDATA" ];   then OPENHAB_USERDATA="$WorkingDir/userdata"; fi
-  if [ -z "$OPENHAB_BACKUPS" ];     then OPENHAB_BACKUPS="$WorkingDir/backups"; fi
+  if [ -z "$OPENHAB_CONF" ];  then OPENHAB_CONF="$WorkingDir/conf"; fi
+  if [ -z "$OPENHAB_USERDATA" ]; then OPENHAB_USERDATA="$WorkingDir/userdata"; fi
+  if [ -z "$OPENHAB_BACKUPS" ]; then OPENHAB_BACKUPS="$WorkingDir/backups"; fi
+  if [ -z "$OPENHAB_RUNTIME" ]; then OPENHAB_RUNTIME="$WorkingDir/runtime"; fi
 
   echo "Using '$OPENHAB_CONF' as conf folder..."
   echo "Using '$OPENHAB_USERDATA' as userdata folder..."
+  echo "Using '$OPENHAB_RUNTIME' as runtime folder..."
+
+  fileList="$OPENHAB_RUNTIME/bin/userdata_sysfiles.lst"
 
   timestamp=$(date +"%y_%m_%d-%H_%M_%S")
   ## Set the filename
@@ -111,20 +115,15 @@ cp -a "${OPENHAB_CONF:?}/"*      "$TempDir/conf"
 
 ## Remove non-transferable userdata files
 echo "Removing unnecessary files..."
-rm -rf "$TempDir/userdata/cache"
-rm -rf "$TempDir/userdata/tmp"
-rm -rf "$TempDir/userdata/etc/all.policy"
-rm -rf "$TempDir/userdata/etc/branding.properties"
-rm -rf "$TempDir/userdata/etc/branding-ssh.properties"
-rm -rf "$TempDir/userdata/etc/config.properties"
-rm -rf "$TempDir/userdata/etc/custom.properties"
-rm -rf "$TempDir/userdata/etc/version.properties"
-rm -rf "$TempDir/userdata/etc/distribution.info"
-rm -rf "$TempDir/userdata/etc/jre.properties"
-rm -rf "$TempDir/userdata/etc/profile.cfg"
-rm -rf "$TempDir/userdata/etc/startup.properties"
-rm -rf "$TempDir/userdata/etc/org.apache.karaf"*
-rm -rf "$TempDir/userdata/etc/org.ops4j.pax.url.mvn.cfg"
+if [ -f "$fileList" ]; then
+  while IFS= read -r fileName
+  do
+    rm -rf "$TempDir/userdata/etc/$fileName"
+  done < "$fileList"
+else
+  echo "System Filelist not found, exiting..."
+  exit 1
+fi
 
 ## If the backup directory is inside userdata folder do not include it
 ## Mainly for apt/rpm automatic
diff --git a/distributions/openhab/src/main/resources/bin/update b/distributions/openhab/src/main/resources/bin/update
--- a/distributions/openhab/src/main/resources/bin/update
+++ b/distributions/openhab/src/main/resources/bin/update
@@ -28,14 +28,14 @@ setup(){
 
   ## Second parameter can be the openHAB path, if not assume the script is called from root!
   if [ -z "$2" ]; then
-    if [ -n "$OPENHAB_HOME" ]; then 
+    if [ -n "$OPENHAB_HOME" ]; then
       WorkingDir="$OPENHAB_HOME"
       DirError="'OPENHAB_HOME' does not point towards openHAB's root directory."
     else
       WorkingDir="."
       DirError="The script must be called from openHAB's root directory."
     fi
-  else 
+  else
     WorkingDir="$2"
     DirError="The specified directory is not openHAB's root directory."
   fi
@@ -259,22 +259,21 @@ echo ""
 echo "Removing openHAB System Files..."
 mkdir -p "$TempDir/runtime"
 mkdir -p "$TempDir/userdata/etc"
-mv "$WorkingDir/runtime"                                "$TempDir/runtime/"
-mv "$WorkingDir/userdata/etc/all.policy"                "$TempDir/userdata/etc/"
-mv "$WorkingDir/userdata/etc/branding.properties"       "$TempDir/userdata/etc/"
-mv "$WorkingDir/userdata/etc/branding-ssh.properties"   "$TempDir/userdata/etc/"
-mv "$WorkingDir/userdata/etc/config.properties"         "$TempDir/userdata/etc/"
-mv "$WorkingDir/userdata/etc/custom.properties"         "$TempDir/userdata/etc/"
-mv "$WorkingDir/userdata/etc/custom.system.properties"  "$TempDir/userdata/etc/"
-mv "$WorkingDir/userdata/etc/distribution.info"         "$TempDir/userdata/etc/"
-mv "$WorkingDir/userdata/etc/jre.properties"            "$TempDir/userdata/etc/"
-mv "$WorkingDir/userdata/etc/org.apache.karaf"*         "$TempDir/userdata/etc/"
-mv "$WorkingDir/userdata/etc/org.apache.felix"*         "$TempDir/userdata/etc/"
-mv "$WorkingDir/userdata/etc/org.ops4j.pax.url.mvn.cfg" "$TempDir/userdata/etc/"
-mv "$WorkingDir/userdata/etc/profile.cfg"               "$TempDir/userdata/etc/"
-mv "$WorkingDir/userdata/etc/startup.properties"        "$TempDir/userdata/etc/"
-mv "$WorkingDir/userdata/etc/system.properties"         "$TempDir/userdata/etc/"
-mv "$WorkingDir/userdata/etc/version.properties"        "$TempDir/userdata/etc/"
+mv "$WorkingDir/runtime" "$TempDir/runtime/"
+
+## Go through a list of system files that are stored in the update archive.
+echo "New system filelist required, extracting from zip..."
+unzip -qp "$OutputFile" runtime/bin/userdata_sysfiles.lst > "$TempDir/filelist.lst" || {
+  echo "System Filelist not found in update, exiting..."
+  exit 1
+}
+while IFS= read -r fileName
+do
+  fullPath="$WorkingDir/userdata/etc/$fileName"
+  if [ -f "$fullPath" ]; then
+    mv "$fullPath" "$TempDir/userdata/etc/"
+  fi
+done < "$TempDir/filelist.lst"
 
 ## Clearing the cache and tmp folders is necessary for upgrade.
 echo "Clearing cache..."
